package ui.tester;
/**
 * Report Bug Form - Form to create new bug
 * @author Ammar
 */

// import for Files
import enums.BugSeverityEnum;
import dao.BugDAO;
import dao.UserDAO; 
import java.io.File;

// import for GUI
import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class ReportBugForm extends javax.swing.JDialog {

    /**
     * Creates new form ReportBugForm
     */
    public ReportBugForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bugTitleLabel = new javax.swing.JLabel();
        bugDiscriptionLabel = new javax.swing.JLabel();
        bugTitleText = new javax.swing.JTextField();
        bugDescriptionText = new java.awt.TextArea();
        assignBugBtn = new javax.swing.JButton();
        severityList = new javax.swing.JComboBox<>();
        severityLabel = new javax.swing.JLabel();
        developerLabel = new javax.swing.JLabel();
        devList = new javax.swing.JComboBox<>();
        PoCLabel = new javax.swing.JLabel();
        addPoCBtn = new javax.swing.JButton();

        setTitle("Report New Bug");

        bugTitleLabel.setText("Title");

        bugDiscriptionLabel.setText("Description");

        assignBugBtn.setText("Assign Bug");
        assignBugBtn.addActionListener(this::assignBugBtnActionPerformed);

        severityList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Critical", "High", "Medium", "low", "info" }));

        severityLabel.setText("Severity");

        developerLabel.setText("Developer");

        devList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dev1", "Dev2", "Dev3", "Dev4" }));

        PoCLabel.setText("PoC");

        addPoCBtn.setText("Add PoC");
        addPoCBtn.addActionListener(this::addPoCBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(devList, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(258, 258, 258))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bugTitleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(severityLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bugDiscriptionLabel)
                                .addComponent(PoCLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(bugDescriptionText, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bugTitleText)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(severityList, 0, 102, Short.MAX_VALUE)
                                .addGap(66, 66, 66)
                                .addComponent(developerLabel)
                                .addGap(211, 211, 211))
                            .addComponent(addPoCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(assignBugBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(147, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bugTitleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bugTitleLabel))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bugDescriptionText, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bugDiscriptionLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(severityLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(severityList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(developerLabel)
                    .addComponent(devList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PoCLabel)
                    .addComponent(addPoCBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(assignBugBtn)
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void assignBugBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assignBugBtnActionPerformed
        // Assign Bug to developer -> save info on text files, and clear the form
        // list them depending on priorty
    }//GEN-LAST:event_assignBugBtnActionPerformed

    private void addPoCBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPoCBtnActionPerformed
        openFileChooser();
    }//GEN-LAST:event_addPoCBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel PoCLabel;
    private javax.swing.JButton addPoCBtn;
    private javax.swing.JButton assignBugBtn;
    private java.awt.TextArea bugDescriptionText;
    private javax.swing.JLabel bugDiscriptionLabel;
    private javax.swing.JLabel bugTitleLabel;
    private javax.swing.JTextField bugTitleText;
    private javax.swing.JComboBox<String> devList;
    private javax.swing.JLabel developerLabel;
    private javax.swing.JLabel severityLabel;
    private javax.swing.JComboBox<String> severityList;
    // End of variables declaration//GEN-END:variables

    // Logic of variables
    BugSeverityEnum severity;
    
    // methods
    private void openFileChooser(){
        JFileChooser fileChooser = new JFileChooser();
        
        fileChooser.setDialogTitle("Choose file of the proof of concept");
        // show file chooser
        int userSelection = fileChooser.showOpenDialog(this);
        
        // check if user choosed a file
        if(userSelection == JFileChooser.APPROVE_OPTION){
            File selectedFile = fileChooser.getSelectedFile();
            
        }
    }
}
